ASUniversity/presentation/ASUniversity.MVC/Areas/Admin/Controllers/ExamController.cs
using ASUniversity.Application.Abstractions.Services;
using ASUniversity.Application.DTOs.Exam;
using ASUniversity.Domain.Enums;
using ASUniversity.Persistence.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASUniversity.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExamController : Controller
    {
        private readonly IExamService _service;
        private readonly ISubjectService _subjectService;
        private readonly ITeacherService _teacherService;
        private readonly IGroupService _groupService;

        public ExamController(IExamService service, ISubjectService subjectService, ITeacherService teacherService, IGroupService groupService)
        {
            _service = service;
            _subjectService = subjectService;
            _groupService = groupService;
        }
        public async Task<IActionResult> Index(int page, int take)
        {
            IEnumerable<ExamItemDto> exams = await _service.GetAllAsync(page, take);
            return View(exams);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ExamCreateDto examDto = new ExamCreateDto()
            {
                Groups = await _groupService.GetAllSelectAsync(),
                Teachers = await _teacherService.GetAllSelectAsync(),
                ExamTypes = Enum.GetValues(typeof(ExamType))
                        .Cast<ExamType>()
                        .Select(p => new SelectListItem
                        {
                            Value = ((int)p).ToString(),
                            Text = EnumHelper.GetEnumDescription(p)
                        })
                        .ToList(),
                Subjects = await _subjectService.GetAllSelectAsync()
            };
            return View(examDto);
        }
        [HttpPost]
        public async Task<IActionResult> Create(ExamCreateDto examCreateDto)
        {
            if (!ModelState.IsValid) return View(examCreateDto);
            await _service.CreateAsync(examCreateDto);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id)
        {
            ExamUpdateDto examUpdateDto = await _service.GetByIdUpdateAsync(id);
            examUpdateDto.Groups = await _groupService.GetAllSelectAsync();
            examUpdateDto.Teachers = await _teacherService.GetAllSelectAsync();
            examUpdateDto.ExamTypes = Enum.GetValues(typeof(ExamType))
                        .Cast<ExamType>()
                        .Select(p => new SelectListItem
                        {
                            Value = ((int)p).ToString(),
                            Text = EnumHelper.GetEnumDescription(p)
                        })
                        .ToList();
            examUpdateDto.Subjects = await _subjectService.GetAllSelectAsync();
            return View(examUpdateDto);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, ExamUpdateDto examUpdateDto)
        {
            if (!ModelState.IsValid) return View(examUpdateDto);
            await _service.Update(id, examUpdateDto);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ASUniversity/presentation/ASUniversity.MVC/Areas/Admin/Controllers/SubjectController.cs
using ASUniversity.Application.Abstractions.Services;
using ASUniversity.Application.DTOs.Subject;
using Microsoft.AspNetCore.Mvc;

namespace ASUniversity.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubjectController : Controller
    {
        private readonly ISubjectService _service;
        private readonly IFacultyService _facultyService;

        public SubjectController(ISubjectService service, IFacultyService facultyService)
        {
            _service = service;
            _facultyService = facultyService;
        }
        public async Task<IActionResult> Index(int page = 1, int take = 5)
        {
            IEnumerable<SubjectItemDto> subjectItemDtos = await _service.GetAllAsync(page, take);
            return View(subjectItemDtos);
        }
        public async Task<IActionResult> Create()
        {
            SubjectCreateDto subjectCreateDto = new SubjectCreateDto()
            {
                Faculties = await _facultyService.GetAllSelectAsync()
            };
            return View(subjectCreateDto);
        }
        [HttpPost]
        public async Task<IActionResult> Create(SubjectCreateDto subjectCreateDto)
        {
            subjectCreateDto.Faculties = await _facultyService.GetAllSelectAsync();
            if (!ModelState.IsValid) return View(subjectCreateDto);
            await _service.CreateAsync(subjectCreateDto, ModelState);
            if (ModelState.ErrorCount > 0)
            {
                ModelState.AddModelError(nameof(subjectCreateDto.Name), "slam");
                return View(subjectCreateDto);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null || id < 1) return BadRequest();
            SubjectUpdateDto subjectUpdateDto = await _service.GetByIdUpdateAsync(id.Value);
            subjectUpdateDto.Faculties = await _facultyService.GetAllSelectAsync();

            return View(subjectUpdateDto);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id, SubjectUpdateDto subjectUpdateDto)
        {
            if (id < 1 || id is null) return BadRequest();
            await _service.Update(id.Value, subjectUpdateDto);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id < 1 || id is null) return BadRequest();
            await _service.Delete(id.Value);
            return RedirectToAction(nameof(Index));
        }
    }
}

ASUniversity/presentation/ASUniversity.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="fixed dark">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<title>Dark Layout | Porto Admin - Responsive HTML5 Template</title>

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="~/Admin/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="~/Admin/vendor/animate/animate.compat.css">
		<link rel="stylesheet" href="~/Admin/vendor/font-awesome/css/all.min.css" />
		<link rel="stylesheet" href="~/Admin/vendor/boxicons/css/boxicons.min.css" />
		<link rel="stylesheet" href="~/Admin/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="~/Admin/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css" />
		<link rel="stylesheet" href="~/Admin/vendor/jquery-ui/jquery-ui.css" />
		<link rel="stylesheet" href="~/Admin/vendor/jquery-ui/jquery-ui.theme.css" />
		<link rel="stylesheet" href="~/Admin/vendor/bootstrap-multiselect/css/bootstrap-multiselect.css" />
		<link rel="stylesheet" href="~/Admin/vendor/morris/morris.css" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="~/Admin/css/theme.css" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="~/Admin/css/skins/default.css" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="~/Admin/css/custom.css">

		<!-- Head Libs -->
		<script src="~/Admin/vendor/modernizr/modernizr.js"></script>

	</head>
	<body>
		<section class="body">

			<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<a href="../4.2.0" class="logo">
						<img src="~/Admin/img/logo.png" width="75" height="35" alt="Porto Admin" />
					</a>

					<div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fas fa-bars" aria-label="Toggle sidebar"></i>
					</div>

				</div>

			
			</header>
			<!-- end: header -->

			<div class="inner-wrapper">
				<!-- start: sidebar -->
				<aside id="sidebar-left" class="sidebar-left">

				    <div class="sidebar-header">
				        <div class="sidebar-title">
				            Navigation
				        </div>
				        <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
				            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
				        </div>
				    </div>

				    <div class="nano">
				        <div class="nano-content">
				            <nav id="menu" class="nav-main" role="navigation">

				                <ul class="nav nav-main">
				                    <li>
				                        <a class="nav-link" asp-action="index" asp-controller="home" asp-area="admin">
				                            <i class="bx bx-home-alt" aria-hidden="true"></i>
				                            <span>Dashboard</span>
				                        </a>                        
				                    </li>
				                    <li class="nav-parent">
				                        <a class="nav-link" href="#">
				                            <i class="bx bx-cart-alt" aria-hidden="true"></i>
				                            <span>Pages</span>
				                        </a>
				                        <ul class="nav nav-children">
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="specialization">
				                                    Specializations
				                                </a>
				                            </li>
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="faculty">
				                                    Faculties
				                                </a>
				                            </li>
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="group">
				                                     Groups
				                                </a>
				                            </li>
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="students">
				                                    Students
				                                </a>
				                            </li>
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="Teacher">
				                                    Teachers
				                                </a>
				                            </li>
				                            <li>
											<a class="nav-link" asp-action="index" asp-controller="Exam">
				                                    Exams
				                                </a>
				                            </li>
				                            <li>
				                                <a class="nav-link" asp-action="index" asp-controller="Subject">
				                                    Subjects
				                                </a>
				                            </li>
				                          
				                        </ul>
				                    </li>
				                    <li>
									<a class="nav-link" href="https://mail.google.com/mail/u/0/#inbox" target="_blank">
				                            <span class="float-end badge badge-primary">182</span>
				                            <i class="bx bx-envelope" aria-hidden="true"></i>
				                            <span>Mailbox</span>
				                        </a>                        
				                    </li>
				                   
				                    <li>
				                        <a class="nav-link" asp-action="Register" asp-controller="authentication" >
										<i class="fa-solid fa-user-plus"></i>
				                            <span>Create Student Or Teacher</span>
				                        </a>                        
				                    </li>
				                    
				                    <li>
				                        <a class="nav-link" href="http://themeforest.net/item/porto-responsive-html5-template/4106987?ref=Okler">
				                            <i class="bx bx-window-alt" aria-hidden="true"></i>
				                            <span>Front-End <em class="not-included">(Not Included)</em></span>
				                        </a>                        
				                    </li>
				                    <li>
				                        <a class="nav-link" href="https://www.okler.net/forums/topic/porto-admin-changelog/">
				                            <i class="bx bx-book-alt" aria-hidden="true"></i>
				                            <span>Changelog</span>
				                        </a>                        
				                    </li>

				                </ul>
				            </nav>

				           
				        </div>

				        <script>
				            // Maintain Scroll Position
				            if (typeof localStorage !== 'undefined') {
				                if (localStorage.getItem('sidebar-left-position') !== null) {
				                    var initialPosition = localStorage.getItem('sidebar-left-position'),
				                        sidebarLeft = document.querySelector('#sidebar-left .nano-content');

				                    sidebarLeft.scrollTop = initialPosition;
				                }
				            }
				        </script>

				    </div>

				</aside>
				<!-- end: sidebar -->
@RenderBody()
		</div>

		<aside id="sidebar-right" class="sidebar-right">
			<div class="nano">
				<div class="nano-content">
					<a href="#" class="mobile-close d-md-none">
						Collapse <i class="fas fa-chevron-right"></i>
					</a>

					<div class="sidebar-right-wrapper">

						<div class="sidebar-widget widget-calendar">
							<h6>Upcoming Tasks</h6>
							<div data-plugin-datepicker data-plugin-skin="dark"></div>

							<ul>
								<li>
									<time datetime="2023-04-19T00:00+00:00">04/19/2023</time>
									<span>Company Meeting</span>
								</li>
							</ul>
						</div>

						<div class="sidebar-widget widget-friends">
							<h6>Friends</h6>
							<ul>
								<li class="status-online">
									<figure class="profile-picture">
										<img src="~/Admin/img/!sample-user.jpg" alt="Joseph Doe" class="rounded-circle">
									</figure>
									<div class="profile-info">
										<span class="name">Joseph Doe Junior</span>
										<span class="title">Hey, how are you?</span>
									</div>
								</li>
								<li class="status-online">
									<figure class="profile-picture">
										<img src="~/Admin/img/!sample-user.jpg" alt="Joseph Doe" class="rounded-circle">
									</figure>
									<div class="profile-info">
										<span class="name">Joseph Doe Junior</span>
										<span class="title">Hey, how are you?</span>
									</div>
								</li>
								<li class="status-offline">
									<figure class="profile-picture">
										<img src="~/Admin/img/!sample-user.jpg" alt="Joseph Doe" class="rounded-circle">
									</figure>
									<div class="profile-info">
										<span class="name">Joseph Doe Junior</span>
										<span class="title">Hey, how are you?</span>
									</div>
								</li>
								<li class="status-offline">
									<figure class="profile-picture">
										<img src="~/Admin/img/!sample-user.jpg" alt="Joseph Doe" class="rounded-circle">
									</figure>
									<div class="profile-info">
										<span class="name">Joseph Doe Junior</span>
										<span class="title">Hey, how are you?</span>
									</div>
								</li>
							</ul>
						</div>

					</div>
				</div>
			</div>
		</aside>

	</section>

	<!-- Vendor -->
	<script src="~/Admin/vendor/jquery/jquery.js"></script>
	<script src="~/Admin/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
	<script src="~/Admin/vendor/popper/umd/popper.min.js"></script>
	<script src="~/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="~/Admin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script src="~/Admin/vendor/common/common.js"></script>
	<script src="~/Admin/vendor/nanoscroller/nanoscroller.js"></script>
	<script src="~/Admin/vendor/magnific-popup/jquery.magnific-popup.js"></script>
	<script src="~/Admin/vendor/jquery-placeholder/jquery.placeholder.js"></script>

	<!-- Specific Page Vendor -->
	<script src="~/Admin/vendor/jquery-ui/jquery-ui.js"></script>
	<script src="~/Admin/vendor/jqueryui-touch-punch/jquery.ui.touch-punch.js"></script>
	<script src="~/Admin/vendor/jquery-appear/jquery.appear.js"></script>
	<script src="~/Admin/vendor/bootstrap-multiselect/js/bootstrap-multiselect.js"></script>
	<script src="~/Admin/vendor/jquery.easy-pie-chart/jquery.easypiechart.js"></script>
	<script src="~/Admin/vendor/flot/jquery.flot.js"></script>
	<script src="~/Admin/vendor/flot.tooltip/jquery.flot.tooltip.js"></script>
	<script src="~/Admin/vendor/flot/jquery.flot.pie.js"></script>
	<script src="~/Admin/vendor/flot/jquery.flot.categories.js"></script>
	<script src="~/Admin/vendor/flot/jquery.flot.resize.js"></script>
	<script src="~/Admin/vendor/jquery-sparkline/jquery.sparkline.js"></script>
	<script src="~/Admin/vendor/raphael/raphael.js"></script>
	<script src="~/Admin/vendor/morris/morris.js"></script>
	<script src="~/Admin/vendor/gauge/gauge.js"></script>
	<script src="~/Admin/vendor/snap.svg/snap.svg.js"></script>
	<script src="~/Admin/vendor/liquid-meter/liquid.meter.js"></script>
	<script src="~/Admin/vendor/jqvmap/jquery.vmap.js"></script>
	<script src="~/Admin/vendor/jqvmap/data/jquery.vmap.sampledata.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/jquery.vmap.world.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.africa.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.asia.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.australia.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.europe.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js"></script>
	<script src="~/Admin/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js"></script>

	<!-- Theme Base, Components and Settings -->
	<script src="~/Admin/js/theme.js"></script>

	<!-- Theme Custom -->
	<script src="~/Admin/js/custom.js"></script>

	<!-- Theme Initialization Files -->
	<script src="~/Admin/js/theme.init.js"></script>

	<!-- Examples -->
	<script src="~/Admin/js/examples/examples.dashboard.js"></script>

</body>
</html>